### ISSUE TITLE
tutorial?

### ISSUE THREAD

**Issue by Ape123454** [Agent-Squad-Productions/extramenu#2]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AgentBUB** [comment]
I know this is a significantly delayed response, but what do you need to be explained in greater detail?

The script has wonderful documentation at: [https://docs.shadowdevs.com/en/opensource/extramenu](https://docs.shadowdevs.com/opensource/extramenu)

**Comment by AgentBUB** [comment]
As no further responses are noted, I will close this. Please open a new issue or contact us via Discord for more help!
