### ISSUE TITLE
Network Event

### ISSUE THREAD

**Issue by aitobh** [Agent-Squad-Productions/extramenu#3]
Hello,
The script is making to much Event, and making crash server

![image](https://user-images.githubusercontent.com/48843742/233844469-2edfc8d4-4874-43b4-b528-58b43efd5b7c.png)

![image](https://user-images.githubusercontent.com/48843742/233844465-80ba6839-0ec2-4eb7-b751-211a135d21c7.png)

![image](https://user-images.githubusercontent.com/48843742/233844479-6b997f48-8523-4e38-a0d9-cdea0e85c1be.png)

**Comment by AgentBUB** [comment]
I will take a look into this when I get a chance. I think I know the solution, but I am busy currently so it may take a bit for me to get to it, sorry.

**Comment by AgentBUB** [comment]
Check out the latest release as this issue should be resolved.

#### [Latest Release](https://github.com/Shadow-Develops/extramenu/releases/tag/v3.2.0)
