### ISSUE TITLE
Version error

### ISSUE THREAD

**Issue by LukasTheDev** [Agent-Squad-Productions/extramenu#5]
You have to fix the version number or contact github because this error
https://raw.githubusercontent.com/Shadow-Develops/version-api/main/extramenu.json

**Comment by LukasTheDev** [comment]
![image](https://github.com/Shadow-Develops/extramenu/assets/145153014/b54f1ea0-d23b-471f-8579-b8c8a4235cde)

**Comment by AgentBUB** [comment]
My fault, forgot to update the version API. Will be all sorted out now.
